apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-db
spec:
  template:
    spec:
      containers:
        - name: mariadb
          env:
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: db-login
                  key: user
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-login
                  key: password
