apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-db
spec:
  template:
    spec:
      containers:
        - name: mariadb
          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mysql/data
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-data
