apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-db
spec:
  template:
    spec:
      containers:
        - name: mariadb
          env:
            - name: MARIADB_USER
              $patch: delete
            - name: MARIADB_PASSWORD
              $patch: delete
