apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-challenge
spec:
  template:
    spec:
      containers:
        - name: wordpress
          env:
            - name: WORDPRESS_DB_USER
              $patch: delete
            - name: WORDPRESS_DB_PASSWORD
              $patch: delete
