apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

commonLabels:
  app: wordpress-challenge

resources:
- ../base
- pvc.yaml
- login.yaml


secretGenerator:
  - name: mariadb-credentials
    behavior: merge
    envs:
      - secrets/mariadb.env
