apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-challenge
spec:
  template:
    spec:
      containers:
        - name: wordpress
          env:
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: login
                  key: user
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: login
                  key: password
