apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-challenge
spec:
  template:
    spec:
      containers:
        - name: wordpress
          volumeMounts:
            - name: mariadb-storage
              mountPath: var/www/html
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-data
