apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-db
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: mariadb
          image: docker.io/library/mariadb:latest
          ports:
            - containerPort: 3306
              name: wordpress-db
          env:
            - name: MARIADB_USER
              value: user1
            - name: MARIADB_PASSWORD
              value: 
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-pass
                  key: root-password
            - name: MARIADB_DATABASE
              value: test-database
