apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-challenge
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: wordpress
          image: docker.io/library/wordpress:latest
          ports:
            - containerPort: 80
              name: http
          env:
            - name: WORDPRESS_DB_HOST
              value: wordpress-db
            - name: WORDPRESS_DB_USER
              value: user1
            - name: WORDPRESS_DB_PASSWORD
              value: 
            - name: WORDPRESS_DB_NAME
              value: test-database
