apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

commonLabels:
  app: wordpress-challenge

resources:
- deployment.yaml
- service.yaml
- route.yaml
- db-deployment.yaml
- db-service.yaml
- root-creds.yaml
